new2/mysite/cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

urlpatterns = [
    path('add_to_cart/', views.add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart/', views.remove_from_cart_view, name='remove_from_cart'),
    path('remove_all_cart/', views.remove_all_from_cart_view, name='remove_all_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('change_item_qty/', views.change_item_qty, name='change_item_qty'),
]

new2/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('part1.urls')),
    path('', include('register.urls')),
    path('', include('search_plus_account.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls'))

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new2/mysite/order/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

urlpatterns = [
    path('order/', views.order_create_view, name='create_order'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('thank_you/', TemplateView.as_view(template_name='order/thank_you.html'), name='thank_you'),
    path('make_order/', views.make_order_view, name='make_order')
]

new2/mysite/order/models.py
from django.db import models

# Create your models here.

new2/mysite/part1/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.models import User


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_check = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = {
            'username',
            'password',
            'password_check',
            'first_name',
            'last_name',
            'email'
        }

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        self.fields['username'].label = "Имя Пользователя"
        self.fields['password'].label = "Пароль"
        self.fields['password'].help_text = "Придумайте Пароль"
        self.fields['password_check'].label = "Повторите пароль"
        self.fields['first_name'].label = "Введите Имя"
        self.fields['last_name'].label = "Введите Фамилию"
        self.fields['email'].label = "Ваша почта"
        self.fields['email'].help_text = "Пожалуйста, указывайте реальный адрес электронной почты"

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        password_check = self.cleaned_data['password_check']
        email = self.cleaned_data['email']

        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователь с данным логином уже зарегистрирован.')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с данным e-mail уже зарегистрирован.')
        if password != password_check:
            raise forms.ValidationError('Пароли не совпадают')


class OrderForm(forms.Form):
    name = forms.CharField()
    last_name = forms.CharField(required=False)
    phone = forms.CharField()
    buying_type = forms.ChoiceField(widget=forms.Select(), choices=([('self', "Самовывоз"), ('delivery', "Доставка")]))
    date = forms.DateField(widget=forms.SelectDateWidget(), initial=timezone.now())
    address = forms.CharField(required=False)
    comments = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['phone'].label = 'Телефон'
        self.fields['phone'].help_text = 'Пожалуйста, указывайте номер по которому с Вами можно связаться'
        self.fields['buying_type'].label = 'Способ получения'
        self.fields['address'].label = 'Адрес'
        self.fields['address'].help_text = 'Укажите Ваш адрес'
        self.fields['comments'].label = 'Комментарии к заказу'
        self.fields['date'].label = 'Дата доставки'
        self.fields['date'].help_text = 'Доставка производится на следующий день после заказа.' \
                                        ' Ожидайте звонка менеджера'


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователь с данным логином не зарегистрирован в системе!')
        user = User.objects.get(username=username)
        if user and not user.check_password(password):
            raise forms.ValidationError('Неверный пароль!')

new2/mysite/order/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from part1.models import Category, Product, Cart, CartItem, Order, Relation
from part1.forms import OrderForm, RegistrationForm, LoginForm
from django.urls import reverse


def checkout_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)

    context = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'order/checkout.html', context)


def order_create_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)

    form = OrderForm(request.POST or None)
    context = {
        'form': form,
        'cart': cart,
        'categories': categories
    }
    return render(request, 'order/order.html', context)


def make_order_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)

    form = OrderForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']
        new_order = Order.objects.create(
            user=request.user,
            items=cart,
            total=cart.cart_total,
            first_name=name,
            last_name=last_name,
            phone=phone,
            address=address,
            buying_type=buying_type,
            comments=comments
        )
        del request.session['cart_id']
        del request.session['total']
        return HttpResponseRedirect(reverse('thank_you'))
    return render(request, 'order/order.html', {'categories': categories})

new2/mysite/mysite/templates/order/checkout.html
{% extends 'part1/index.html' %}

{% block content %}

<title>
{%block title%}
Checkout
{%endblock title%}
</title>

<h2 class="text-center" style="margin-top:20px;">Ваш предварительный заказ</h2>
<hr>
<table class="table">
    <tr>
        <td class="text-center"><strong>Товар</strong></td>
        <td class="text-center"><strong>Кол-во</strong></td>
        <td class="text-center"><strong>Цена</strong></td>
        <td class="text-center"></td>
    </tr>
    {% for item in cart.items.all %}
    <tr>
        <td class="text-center">{{ item.product.title }}</td>
        <td class="text-center">{{ item.qty }}</td>
        <td class="text-center">{{ item.item_total }} грн.</td>
        <td></td>
    </tr>
    {% endfor %}
<tr>
    <td></td>
    <td></td>
    <td class="text-center"><strong>Итого:</strong></td>
    <td class="text-center"><strong>{{cart.cart_total}} грн.</strong></td>
</tr>
</table>
<a href="{% url 'create_order' %}"><button class="btn btn-outline-success">Оформить заказ</button></a>
{% endblock %}

new2/mysite/mysite/templates/order/oplata.html
<div id="liqpay_checkout">

</div>
<script>
    window.LiqPayCheckoutCallback = function() {
    LiqPayCheckout.init({
	data: "eyAidmVyc2lvbiIgOiAzLCAicHVibGljX2tleSIgOiAieW91cl9wdWJsaWNfa2V5IiwgImFjdGlv" +
	"biIgOiAicGF5IiwgImFtb3VudCIgOiAxLCAiY3VycmVuY3kiIDogIlVTRCIsICJkZXNjcmlwdGlv" +
	"biIgOiAiZGVzY3JpcHRpb24gdGV4dCIsICJvcmRlcl9pZCIgOiAib3JkZXJfaWRfMSIgfQ==",
	signature: "QvJD5u9Fg55PCx/Hdz6lzWtYwcI=",
	embedTo: "#liqpay_checkout",
	language: "ru",
	mode: "embed" // embed || popup
    }).on("liqpay.callback", function(data){
    	console.log(data.status);
    	console.log(data);
    }).on("liqpay.ready", function(data){
    	// ready
    }).on("liqpay.close", function(data){
    	// close
    });
};
</script>
<script src="//static.liqpay.ua/libjs/checkout.js" async></script>

new2/mysite/mysite/templates/order/order.html
{% extends 'part1/index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<title>
{%block title%}
Заказ
{%endblock title%}
</title>

<h3 class='text-center' style="margin-top:20px;">Оформление заказа</h3>
<hr>
<form action='{% url "make_order" %}' method="POST">
{% csrf_token %}
<div class='col-sm-4'>
	{{ form.name|as_crispy_field }}
</div>
<div class='col-sm-4'>
	{{ form.last_name|as_crispy_field }}
</div>
<div class='col-sm-4'>
	{{ form.phone|as_crispy_field }}
</div>

{{ form.buying_type|as_crispy_field }}
{{ form.address|as_crispy_field }}
{{ form.date|as_crispy_field }}
{{ form.comments|as_crispy_field }}

<center><input type='submit' class="btn btn-outline-danger btn-lg" value='Оформить заказ' style="margin-bottom:30px;"></center>
</form>
<script src='{% static "js/jquery.min.js" %}'></script>
<script>
	$(document).ready(function(){
		$('#div_id_address').css('display', 'none')
		$('#id_buying_type').on('click', function(){
			buying_type = $(this).val()
			if(buying_type == 'delivery'){
				$('#div_id_address').css('display', 'block')
			}else{
				$('#div_id_address').css('display', 'none')
			}
		})
		$('#id_date_month').css('width', '100px')
		$('#id_date_month').css('display', 'inline')
		$('#id_date_year').css('width', '100px')
		$('#id_date_year').css('display', 'inline')
		$('#id_date_day').css('width', '50px')
		$('#id_date_day').css('display', 'inline')
	})
</script>
{% endblock content %}

new2/mysite/mysite/templates/order/thank_you.html
{% extends 'part1/index.html' %}


{% block content %}
<title>
{%block title%}
Операция прошла успешно
{%endblock title%}
</title>
<div class='col-sm-16 col-sm-offset-2'>
	<h3 class='text-center' style="margin-top:20px;">Спасибо за Ваш заказ! Он принят в обработку. В ближайшее время менеджер с Вами свяжется</h3>
	<p class='text-center'><a href='/'><button class="btn btn-outline-danger btn-lg">Вернуться в покупкам</button></a></p>
</div>

{% endblock content %}